

[mongodb]
mongodb.daws1.shop

[redis]
redis.daws1.shop

[mysql]
mysql.daws1.shop

[rabbitmq]
rabbitmq.daws1.shop

[catalogue]
catalogue.daws1.shop

[user]
user.daws1.shop

[cart]
cart.daws1.shop

[shipping]
shipping.daws1.shop


[payment]
payment.daws1.shop 

[frontend]
frontend.daws1.shop

[local]
localhost


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321


