- name: install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql

- name: build shipping application
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: move jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app  

